homography:
  src_points:
  - [590, 690]
  - [914, 674]
  - [1908, 1268]
  - [822, 1406]
  real_width_m: 3.5
  real_length_m: 50.0
  scale_px_per_m: 100
  matrix:
  - [-0.6096003563722957, 0.19752413781895578, 223.37255516457526]
  - [-0.7561465793152746, -15.311968231134493, 11011.384561278817]
  - [-5.00838215476301e-05, -0.0022664225822663837, 1.0]
  image_size: [2560, 1440]
