homography:
  src_points:
  - [494, 248]
  - [678, 244]
  - [2126, 1250]
  - [820, 1418]
  real_width_m: 3.5
  real_length_m: 100.0
  scale_px_per_m: 100
  matrix:
  - [-3.4708276932363447, 0.96708532307269, 1474.751720336729]
  - [-2.811027276868225, -129.30725473590437, 33456.84664927727]
  - [-8.304203429080711e-05, -0.011391039368976195, 1.0]
  image_size: [2560, 1440]
