homography:
  src_points:
  - [359, 76]
  - [577, 57]
  - [1038, 369]
  - [500, 439]
  real_width_m: 4.0
  real_length_m: 60.0
  scale_px_per_m: 100
  matrix:
  - [2.627206211665051, -1.020485057423613, -865.6101656235588]
  - [6.299494148284233, 72.27840654347104, -7754.677296537835]
  - [0.00045816832198939436, 0.007498399880113849, 1.0]
  image_size: [1920, 1080]
