homography:
  src_points:
  - [170, 178]
  - [474, 166]
  - [2012, 1146]
  - [556, 1412]
  real_width_m: 3.5
  real_length_m: 30.0
  scale_px_per_m: 100
  matrix:
  - [3.6376476943983302, -1.1378703484908868, -415.85918601633864]
  - [1.8203221845139097, 46.11482867435513, -8517.894275402563]
  - [0.00014336171845444898, 0.012835036733001556, 0.9999999999999999]
  image_size: [2560, 1440]
